services:
  wrnum_postgre:
    image: postgres:15
    volumes:
      - ./init_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./pg_data/flask-yt:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - wrnum_net

  wrnum_flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: wrnum_flask0
    volumes:
      - ~/.uploads/images/flask-yt:/app/app/static/upload
    environment:
      - POSTGRES_HOST=wrnum_postgre
      - POSTGRES_PORT=5432
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=wrongnumber
    depends_on:
      - wrnum_postgre
    expose:
      - 9855
    restart: always
    networks:
      - wrnum_net

  wrnum_nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: wrnum_nginx0
    depends_on:
      - wrnum_flask
    ports:
      - "9853:80"
    restart: always
    networks:
      - wrnum_net

networks:
  wrnum_net:
    driver: bridge
