services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ~/.pg/pg_data/flask-yt:/var/lib/postgresql/data
    ports:
      - "54321:5432"
  flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask
    volumes:
      - ~/.uploads/images/flask-yt:/app/app/static/upload
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=wrongnumber
    depends_on:
      - postgres
    expose:
      - 9855
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: nginx
    depends_on:
      - flask
    ports:
      - "9853:80"
