"""empty message

Revision ID: 5f48c23e50c2
Revises: 74af92c68ab6
Create Date: 2025-03-14 18:04:42.998255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f48c23e50c2'
down_revision = '74af92c68ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_id', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['flag_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('flag_id')

    # ### end Alembic commands ###
