"""empty message

Revision ID: 74af92c68ab6
Revises: fe789a46cba5
Create Date: 2025-03-14 15:51:27.923411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74af92c68ab6'
down_revision = 'fe789a46cba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('number', schema=None) as batch_op:
        batch_op.drop_constraint('number_owner_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('number', schema=None) as batch_op:
        batch_op.create_unique_constraint('number_owner_id_key', ['owner_id'])

    # ### end Alembic commands ###
