"""empty message

Revision ID: fe789a46cba5
Revises: 49be378985da
Create Date: 2025-03-14 00:32:55.064844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe789a46cba5'
down_revision = '49be378985da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'number', ['number_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('number_id')

    # ### end Alembic commands ###
